/**
 * Mock Event Data
 * Realistic event data with varied dates and types
 */
import { EventCardProps } from '@eventfit/types';

export const mockEvents: EventCardProps[] = [
  {
    id: 'evt_carolina_lights',
    title: 'Carolina Lights',
    coverPhoto: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 0.9,
    tags: ['concert', 'nightlife'],
    hasRentals: true,
    organizer: { name: 'Golden Records' },
  },
  {
    id: 'evt_spring_formal',
    title: 'Spring Formal',
    coverPhoto: 'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 1.2,
    tags: ['formal', 'social'],
    hasRentals: true,
    organizer: { name: 'Student Government' },
  },
  {
    id: 'evt_gameday_tailgate',
    title: 'Gameday Tailgate',
    coverPhoto: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 0.5,
    tags: ['gameday', 'social'],
    hasRentals: false,
    organizer: { name: 'Football Fan Club' },
  },
  {
    id: 'evt_charity_fashion',
    title: 'Charity Fashion Show',
    coverPhoto: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 1.5,
    tags: ['fashion', 'charity'],
    hasRentals: true,
    organizer: { name: 'Fashion Society' },
  },
  {
    id: 'evt_homecoming',
    title: 'Homecoming Block Party',
    coverPhoto: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 2.1,
    tags: ['gameday', 'party'],
    hasRentals: true,
    organizer: { name: 'Alumni Association' },
  },
  {
    id: 'evt_winter_ball',
    title: 'Winter Ball',
    coverPhoto: 'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 0.8,
    tags: ['formal', 'dance'],
    hasRentals: true,
    organizer: { name: 'Greek Life Council' },
  },
  {
    id: 'evt_concert_night',
    title: 'Concert Night',
    coverPhoto: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 1.0,
    tags: ['concert', 'music'],
    hasRentals: true,
    organizer: { name: 'Music Club' },
  },
  {
    id: 'evt_date_night',
    title: 'Date Night Social',
    coverPhoto: 'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&h=300&fit=crop',
    startAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    campus: 'UNC Chapel Hill',
    distanceMiles: 0.7,
    tags: ['social', 'date night'],
    hasRentals: true,
    organizer: { name: 'Social Events Committee' },
  },
];
