/**
 * Mock Inspiration Data
 * Curated outfit inspiration images
 */
import { InspirationCardProps } from '../../components/inspiration/InspirationCard';

export const mockInspiration: InspirationCardProps[] = [
  {
    id: 'insp_formal_1',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=600&fit=crop',
    title: 'Classic Black Tie Look',
    description: 'Perfect for formal events and galas',
    source: 'Pinterest',
    affiliateLink: 'https://example.com/shop/formal-1',
    eventType: 'Formal',
    likesCount: 142,
    matchingRentalsCount: 3,
  },
  {
    id: 'insp_gameday_1',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=500&fit=crop',
    title: 'Gameday Spirit Outfit',
    description: 'Show your school spirit in style',
    source: 'Instagram',
    eventType: 'Gameday',
    likesCount: 289,
    matchingRentalsCount: 5,
  },
  {
    id: 'insp_concert_1',
    image: 'https://images.unsplash.com/photo-1594633312688-8f5f2943066a?w=400&h=700&fit=crop',
    title: 'Concert Ready',
    description: 'Edgy and cool for a night out',
    source: 'TikTok',
    eventType: 'Concert',
    likesCount: 320,
    matchingRentalsCount: 2,
  },
  {
    id: 'insp_date_1',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=550&fit=crop',
    title: 'Date Night Chic',
    description: 'Elegant and effortless',
    source: 'Pinterest',
    affiliateLink: 'https://example.com/shop/date-1',
    eventType: 'Date Night',
    likesCount: 155,
    matchingRentalsCount: 4,
  },
  {
    id: 'insp_formal_2',
    image: 'https://images.unsplash.com/photo-1566479179817-1c5df86abf55?w=400&h=650&fit=crop',
    title: 'Evening Gown Elegance',
    description: 'Stunning for special occasions',
    source: 'Pinterest',
    affiliateLink: 'https://example.com/shop/formal-2',
    eventType: 'Formal',
    likesCount: 198,
    matchingRentalsCount: 6,
  },
  {
    id: 'insp_casual_1',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=450&fit=crop',
    title: 'Spring Fling Vibes',
    description: 'Light and airy for outdoor events',
    source: 'Pinterest',
    eventType: 'Casual',
    likesCount: 78,
    matchingRentalsCount: 1,
  },
  {
    id: 'insp_gameday_2',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=600&fit=crop',
    title: 'Tailgate Ready',
    description: 'Comfortable and stylish',
    source: 'Instagram',
    eventType: 'Gameday',
    likesCount: 167,
    matchingRentalsCount: 3,
  },
  {
    id: 'insp_concert_2',
    image: 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400&h=550&fit=crop',
    title: 'Concert Night Outfit',
    description: 'Bold and fun for live music',
    source: 'TikTok',
    eventType: 'Concert',
    likesCount: 234,
    matchingRentalsCount: 2,
  },
  {
    id: 'insp_formal_3',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=600&fit=crop',
    title: 'Winter Formal Look',
    description: 'Perfect for cold weather formals',
    source: 'Pinterest',
    affiliateLink: 'https://example.com/shop/formal-3',
    eventType: 'Formal',
    likesCount: 201,
    matchingRentalsCount: 4,
  },
  {
    id: 'insp_date_2',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=500&fit=crop',
    title: 'Romantic Dinner Outfit',
    description: 'Sweet and sophisticated',
    source: 'Instagram',
    eventType: 'Date Night',
    likesCount: 133,
    matchingRentalsCount: 3,
  },
];
